### ISSUE TITLE
[Error] Run node app.js

### ISSUE THREAD

**Issue by baliomega** [fakhrullah/nasihati#14]
Ada error bila saya run **'node app.js'**.

```KL-PT-065:nasihati izwan$ node app.js
module.js:472
    throw err;
    ^

Error: Cannot find module './config.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/izwan/Documents/Baliomega/nasihati/app.js:9:14)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

**Comment by fakhrullah** [comment]
Jap2. Saya akan try deploy dekat pc orang lain, malam ni, pastu tulis step by step, cara run.
Laptop sy ram 4GB je, xleh nak guna virtualbox.

**Comment by fakhrullah** [comment]
Oh, caranya copy config.sample.js, pastu rename ke config.js. 
Saya gitignore `config.js` spy masing2 boleh set config sendiri.

Satu lagi, xboleh run lagi kot. Nak kena ada data di MongoDB.

**Comment by fakhrullah** [comment]
Tak de PC lain nak test. Try cuba step2 ni https://github.com/fakhrullah/nasihati/tree/doc/add-guide-how-to-run#cara-guna

File nasihat.json ada dalam branch `doc/add-guide-how-to-run`

**Comment by baliomega** [comment]
Ok saya cuba dahulu. If there is an issue, I'll raise here. Thanks!

**Comment by baliomega** [comment]
Salam. Untuk link step di atas sila update URL ke https://github.com/fakhrullah/nasihati#cara-pasang-install

Saya dah ikut step yang diberikan dan bila run 'node app.js' akan keluar 'Example app listening on port 3000!'.  Untuk view page tersebut saya perlu buka di 'http://localhost:3000/' tapi error seperti di bawah akan keluar.

```
show a quote for today
2016-12-15
1st time user
today quote id = 1

/Users/izwan/Documents/Baliomega/nasihati/node_modules/mongodb/lib/mongo_client.js:224
          throw err
          ^
MongoError: failed to connect to server [localhost:27017] on first connect
    at Pool.<anonymous> (/Users/izwan/Documents/Baliomega/nasihati/node_modules/mongodb-core/lib/topologies/server.js:325:35)
    at emitOne (events.js:96:13)
    at Pool.emit (events.js:188:7)
    at Connection.<anonymous> (/Users/izwan/Documents/Baliomega/nasihati/node_modules/mongodb-core/lib/connection/pool.js:270:12)
    at Connection.g (events.js:292:16)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:191:7)
    at Socket.<anonymous> (/Users/izwan/Documents/Baliomega/nasihati/node_modules/mongodb-core/lib/connection/connection.js:173:49)
    at Socket.g (events.js:292:16)
    at emitOne (events.js:96:13)
```

**Comment by baliomega** [comment]
Atau error di atas disebabkan oleh data MongoDB. Bila saya run `mongoimport --db nasihat --collection nasihats --type json --file nasihat.json` error seperti di bawah akan keluar.

```
2016-12-15T23:03:33.187+0800	[........................] nasihat.nasihats	0B/70.9KB (0.0%)
2016-12-15T23:03:33.719+0800	[........................] nasihat.nasihats	0B/70.9KB (0.0%)
2016-12-15T23:03:33.719+0800	Failed: error connecting to db server: no reachable servers
2016-12-15T23:03:33.719+0800	imported 0 documents
```

**Comment by fakhrullah** [comment]
mongodb dah start belum? cuba test mongo command line.

Kalau mongodb tak start lagi, ini error bila run `mongo`. _sori, tulisan jepun, abaikan je_

```
fakhrullah@fakhrullah-UX MINGW64 ~
$ mongo
2016-12-16T11:42:04.478+0800 I CONTROL  [main] Hotfix KB2731284 or later update is not installed, will zero-out data files
MongoDB shell version: 3.2.4
connecting to: test
2016-12-16T11:42:05.552+0800 W NETWORK  [thread1] Failed to connect to 127.0.0.1:27017, reason: errno:10061 対象のコンピューターによって拒否されたため、接続できませんでした。
2016-12-16T11:42:05.553+0800 E QUERY    [thread1] Error: couldn't connect to server 127.0.0.1:27017, connection attempt failed :
connect@src/mongo/shell/mongo.js:224:14
@(connect):1:6

exception: connect failed
```

Cara start mongodb. run `mongod`. Dekat Windows saya buka `git bash` lain semata2 untuk run `mongod`. Dekat ubuntu server, automatik run bila reboot.

**Comment by fakhrullah** [comment]
Saya dah test, kedua error sebab mongodb tak start lg. Kecuali, jika port mongodb ditukar ke port lain, ada tukar port mongodb kah?

**Comment by baliomega** [comment]
Ok dah run `mongod` kat terminal tab satu lagi. Kemudian saya run `node app.js` kat terminal tab lain dan keluar `Example app listening on port 3000!`. Bila buka `http://localhost:3000/` di browser keluar error berikut di dalam terminal.

```
show a quote for today
2016-12-16
1st time user
today quote id = 1
/Users/izwan/Documents/Baliomega/nasihati/node_modules/mongodb/lib/utils.js:98
    process.nextTick(function() { throw err; });
                                  ^

TypeError: Cannot read property 'text' of undefined
    at /Users/izwan/Documents/Baliomega/nasihati/app.js:83:21
    at /Users/izwan/Documents/Baliomega/nasihati/nasihat_col.js:23:9
    at handleCallback (/Users/izwan/Documents/Baliomega/nasihati/node_modules/mongodb/lib/utils.js:95:56)
    at /Users/izwan/Documents/Baliomega/nasihati/node_modules/mongodb/lib/cursor.js:852:16
    at handleCallback (/Users/izwan/Documents/Baliomega/nasihati/node_modules/mongodb-core/lib/cursor.js:171:5)
    at setCursorNotified (/Users/izwan/Documents/Baliomega/nasihati/node_modules/mongodb-core/lib/cursor.js:516:3)
    at /Users/izwan/Documents/Baliomega/nasihati/node_modules/mongodb-core/lib/cursor.js:591:16
    at queryCallback (/Users/izwan/Documents/Baliomega/nasihati/node_modules/mongodb-core/lib/cursor.js:232:18)
    at /Users/izwan/Documents/Baliomega/nasihati/node_modules/mongodb-core/lib/connection/pool.js:455:18
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
```

**Comment by fakhrullah** [comment]
`mongoimport --db nasihat --collection nasihats --type json --file nasihat.json` ini run untuk buat database, collections dan document di mongodb.
Jadi, lepas run command tu kena dapat

```
... something ...
... tarikh ...            imported 182 documents
```

kena import documents xboleh kosong. cuba cek mongodb, database n collection dah jadi ke tak?

ni guna git bash. Untuk Ubuntu terminal, buang winpty tu.

```
$ winpty mongo
2016-12-17T07:22:52.022+0800 I CONTROL  [main] Hotfix KB2731284 or later update
is not installed, will zero-out data files
MongoDB shell version: 3.2.4
connecting to: test
> use nasihat
switched to db nasihat
> db.nasihats.count()
182
>
```

**Comment by baliomega** [comment]
Ok jadi!

Apa beza`mongo` dan `mongod`?

Jadi saya ada 2 terminal tab yang perlu di open untuk run code:

1. `node app.js`
2. `mongod`

**Comment by fakhrullah** [comment]
`mongod` untuk start servis mongodb.

`mongo` untuk tengok dlm db, macam phpmyadmin, tanpa gui.

Betul dah 2 tab je, perlu, satu utk run `mongod`, klu XAMPP, biasanya kita guna xampp control panel. satu lg, utk start app `node app.js` utk start web/app.

**Comment by baliomega** [comment]
I see. Terima kasih di atas bantuan anda. Saya close ye issue ini.
